version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:sa123@db:5432/Ritik_db
    depends_on:
      - db
    volumes:
      - .:/HERUKO

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sa123
      POSTGRES_DB: Ritik_db
    ports:
      - "5001:5001"



